/*
===============================================================================
Script Name   : Exploratory Data Analysis (EDA)
File Name     : eda.sql
Database      : Data Warehouse (Gold Layer)
Author        : Sanganna Jalade
Date Created  : 2026-07-27
Description   : 
    This script contains a collection of exploratory queries designed to analyze 
    the enterprise data warehouse. It explores database schema objects, column 
    definitions, domain dimensions, aggregate metrics, grouping/distributions, 
    and ranking analyses across customers, products, and sales performance.

Script Structure:
    1. Database & Schema Exploration
    2. Dimension & Measure Exploration
    3. Aggregate Business Metrics & KPI Summary
    4. Grouping & Distribution Analysis
    5. Ranking & Top/Bottom N Analysis
===============================================================================
*/

USE DataWarehouse; 
GO



-- Explore All objects in the database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore all Columns in the database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME ='dim_customers'

-- Explore All countries our customers come from 
SELECT DISTINCT country FROM gold.dim_customers


-- Explore All Categories "The major Divisions"
SELECT DISTINCT category,subcategory,product_name FROM gold.dim_products
ORDER BY 1,2,3

-- Find the date of the first and last order

SELECT
MIN(order_date) AS first_order_date ,
MAX(order_date) AS last_order_date,
DATEDIFF(year,MIN(order_date),MAX(order_date)) FROM gold.fact_sales

-- FInd the youngest and the oldest customer

SELECT MIN(birthdate) AS oldest_birthdate,
DATEDIFF(YEAR,MIN(birthdate),GETDATE()) AS oldest_age,
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(YEAR,MAX(birthdate),GETDATE()) AS youngest_age
FROM gold.dim_customers

-- Find the Total Sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales

-- Find the total number of orders
SELECT COUNT(DISTINCT(order_number)) AS total_orders FROM gold.fact_sales

-- Find the total number of products
SELECT COUNT(product_key) AS total_products FROM gold.dim_products

-- Find the total number of customers
SELECT COUNT(customer_key) AS total_customers FROM gold.dim_customers

-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT( customer_key)) AS total_customers FROM gold.fact_sales




-- Generate a Report that shows all key metrics of the business

SELECT 'Total Sales' AS measure_name,SUM(sales_amount) AS measure_value FROM gold.fact_sales 
UNION ALL
SELECT 'Total Quantity' AS measure_name,SUM(quantity) AS measure_value FROM gold.fact_sales 
UNION ALL
SELECT 'Average Price',AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Orders',COUNT(DISTINCT Order_number) FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products', COUNT(product_name) FROM gold.dim_products
UNION ALL 
SELECT 'Total Nr. Customers', COUNT(customer_key) FROM gold.dim_customers



-- Find total Customers by countries

SELECT 
country,COUNT(Customer_key) AS total_customers FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customerrs by gender
SELECT 
gender,COUNT(customer_key) AS total_customers FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC


-- find total products by category 
SELECT
category,COUNT(product_name) AS total_products FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- what is the average costs in each category?
SELECT
category,AVG(cost) AS avg_costs FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC

-- what is the total revenue generated for each category ?
SELECT 
p.category ,
SUM(f.sales_amount)AS total_revenue FROM gold.fact_sales f
LEFT JOIN gold.dim_products p ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Find total revenue is generated by each customer

SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c on c.customer_key=f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC


-- what is the distribution of sold items across countries ?
SELECT 
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c on c.customer_key=f.customer_key
GROUP BY
c.country
ORDER BY total_sold_items DESC


--Ranking Analysis 

-- Which 5 products generate the highest revenue ?

SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC

-- What are the 5 worst-performing products in terms of sales?
SELECT TOP 5
	p.product_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key=f.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC



-- find the top 10 customers who have generated the highest revenue
SELECT * FROM (SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue,
ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_customers
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c on c.customer_key=f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
)t
WHERE rank_customers <= 10


-- 3 customers with the fewest orders placed


SELECT TOP 3
	c.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT(f.order_number)) AS total_orders 
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c ON c.customer_key=f.customer_key
GROUP BY  c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders

